# Generated by Django 5.1.4 on 2024-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafemenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='price2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
